trigger:
- master
- dev

jobs:
- template: template.yml
  parameters:
    name: Ubuntu_18_04_python37
    vmImage: 'ubuntu-18.04'
    py_maj: 3
    py_min: 7

- template: template.yml
  parameters:
    name: Ubuntu_20_04_python37
    vmImage: 'ubuntu-20.04'
    py_maj: 3
    py_min: 7

- template: template.yml
  parameters:
    name: macOS_10_14_python37
    vmImage: 'macOS-10.14'
    py_maj: 3
    py_min: 7

- template: template.yml
  parameters:
    name: Windows_VS2019_python37
    vmImage: 'windows-2019'
    py_maj: 3
    py_min: 7
    conda_bld: 3.17
