parameters:
  name: 'Conda build job'
  vmImage: 'Ubuntu-18.04'
  py_maj: '3'
  py_min: '6'
  conda_bld: '3.16.3'

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 360
  
  pool:
    vmImage: ${{ parameters.vmImage }}
    
  steps: 
  
  - ${{ if or(contains(parameters.vmImage, 'macOS'),contains(parameters.vmImage, 'Ubuntu')) }}:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: 'Add conda to PATH'
  - ${{ if contains(parameters.vmImage, 'win') }}:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: 'Add conda to PATH'

  - ${{ if contains(parameters.vmImage, 'macOS') }}:
    - bash: |
        sudo chown -R $USER $CONDA
      displayName: 'MacOS ownership workaround'
 
  - bash: |
        conda config --set always_yes yes --set changeps1 no && \
        conda update -q conda && \
        conda info -a && \
        conda config --add channels https://conda.anaconda.org/conda-forge
    displayName: 'Conda config and info'

  - bash: |
        conda env create -n pyschenv -f environment.yml python=${{ parameters.py_maj }}.${{ parameters.py_min }}
    displayName: Install pyschedule to a deidcated environment
    
  - bash: |
      source activate pyschenv
    displayName: 'Activate environment and run tests'
